name: Android CI


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
#       - name: Analyze with SonarCloud         
#         uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
#         with:
#           # Additional arguments for the sonarcloud scanner
#           args:             
#             # Unique keys of your project and organization. You can find them in SonarCloud > Information (bottom-left menu)
#             # mandatory
#             -Dsonar.projectKey=johanforce_sample_ci
#             -Dsonar.organization=johanforce
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonarqube --info
     
      - name: Distribute App
        run: |
          curl \
            -H "Authorization: token ${{secrets.DEPLOYGATE_KEY_API}}" \
            -F "file=@app/build/outputs/apk/debug/app-debug.apk" \
            -F "message=Any message" \
            -F "distribution_key=${{secrets.DEPLOYGATE_KEY_DISTRIBUTIONS}}" \
            -F "release_note=Release Note" \
            "https://deploygate.com/api/users/johanforce/apps"


      - name: Distribute App 2
        run: |
          curl \
            -H "Content-Type: application/json" \
            -X POST "${{secrets.SHARE_CHAT_GOOGLE_KEY}}" \
            --data "{\"cards\": [{\"sections\":[{\"widgets\":[{\"image\":{\"imageUrl\":\"${{secrets.SHARE_IMAGE_URL}}\",\"altText\":\"\",\"onClick\":{\"openLink\":{\"url\":\"${{secrets.DEPLOYGATE_SHARING_URL}}\"}}}}]},{\"widgets\":[{\"buttons\":[{\"textButton\":{\"text\":\"DOWNLOAD\",\"onClick\":{\"openLink\":{\"url\":\"${{secrets.DEPLOYGATE_SHARING_URL}}\"}}}}]}]}],\"header\":{\"title\":\"The new version is released\",\"imageUrl\":\"https://freecodegenerators.azureedge.net/images/sad-capoo.gif\",\"imageStyle\":\"AVATAR\"}}]}"
