name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Distribute App
        run: |
          curl \
            -H "Authorization: token ${{secrets.DEPLOYGATE_KEY_API}}" \
            -F "file=@app/build/outputs/apk/debug/app-debug.apk" \
            -F "message=Any message" \
            -F "distribution_key=${{secrets.DEPLOYGATE_KEY_DISTRIBUTIONS}}" \
            -F "release_note=Release Note" \
            "https://deploygate.com/api/users/johanforce/apps"


      - name: Distribute App 2
        run: |
          curl \
            -H "Content-Type: application/json" \
            -X POST "${{secrets.SHARE_CHAT_GOOGLE_KEY}}" \
            --data "{\"cards\": [{\"sections\":[{\"widgets\":[{\"image\":{\"imageUrl\":\"${{DEPLOYGATE_DISTRIBUTION_QR_CODE_IMAGE_URL}}\",\"altText\":\"\",\"onClick\":{\"openLink\":{\"url\":\"${{DEPLOYGATE_SHARING_URL}}\"}}}}]},{\"widgets\":[{\"buttons\":[{\"textButton\":{\"text\":\"DOWNLOAD\",\"onClick\":{\"openLink\":{\"url\":\"${{DEPLOYGATE_SHARING_URL}}\"}}}}]}]}],\"header\":{\"title\":\"The new version is released\",\"imageUrl\":\"https://freecodegenerators.azureedge.net/images/sad-capoo.gif\",\"imageStyle\":\"AVATAR\"}}]}"
